---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: az-atarraya-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: az-atarraya-test
        aadpodidbinding: requires-vault
      annotations:
        atarraya/keyvault: <KEYVAULT NAME>
    spec:
      containers:
        - name: testbox
          image: alpine:3.10
          command: ["sh", "-c", "echo $<SECRET NAME>"]
          imagePullPolicy: IfNotPresent
          env:
            - name: ATARRAYA_SECRET_<SECRET NAME>
          resources:
            requests:
              memory: "16Mi"
              cpu: "100m"
            limits:
              memory: "32Mi"
              cpu: "200m"
