apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "atarraya-webhook.name" . }}
  labels:
    app: {{ template "atarraya-webhook.name" . }}
    chart: {{ template "atarraya-webhook.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "atarraya-webhook.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "atarraya-webhook.name" . }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ template "atarraya-webhook.name" . }}-certs
      containers:
        - name: "atarraya-webhook"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          command: ["entrypoint.sh"]
          args: []
          ports:
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: secrets
              mountPath: /var/lib/secrets/cert.crt
              subPath: tls.crt
            - name: secrets
              mountPath: /var/lib/secrets/cert.key
              subPath: tls.key
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: https
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "0.5"
              memory: 1Gi
            limits:
              cpu: "0.5"
              memory: 2Gi
          env:
            - name: "TLS_CERT_FILE"
              value: "/var/lib/secrets/cert.crt"
            - name: "TLS_KEY_FILE"
              value: "/var/lib/secrets/cert.key"
            - name: "LOG_LEVEL"
              value: "2"
