{{- $altNames := list ( printf "%s.%s" (include "atarraya-webhook.name" .) .Release.Namespace ) ( printf "%s.%s.svc" (include "atarraya-webhook.name" .) .Release.Namespace ) -}}
{{- $ca := genCA "atarraya-webhook-ca" 365 -}}
{{- $cert := genSignedCert ( include "atarraya-webhook.name" . ) nil $altNames 365 $ca -}}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "atarraya-webhook.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "atarraya-webhook.name" . }}
    track: prod
webhooks:
  - name: "{{ template "atarraya-webhook.name" . }}.mendible.com"
    failurePolicy: "Ignore" # we fail "open" if the webhook is down hard
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    clientConfig:
      service:
        name: {{ template "atarraya-webhook.name" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate" # what /url/slug to send requests at
      # See README.md for how this was generated!
      caBundle: {{ $ca.Cert | b64enc }}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "atarraya-webhook.name" . }}-certs
  labels:
    app: {{ template "atarraya-webhook.name" . }}
    chart: {{ template "atarraya-webhook.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}