apiVersion: v1
kind: Service
metadata:
  name: {{ template "atarraya-webhook.name" . }}
  labels:
    app: {{ template "atarraya-webhook.name" . }}
    chart: {{ template "atarraya-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    app: {{ template "atarraya-webhook.name" . }}
    release: {{ .Release.Name }}